theme = "ayu_mirage"

[editor]
color-modes = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"," = ":w"
j = "move_char_left"
k = "move_visual_line_down"
l = "move_char_right"
i = "move_visual_line_up"
h = "insert_mode"
H = "insert_at_line_start"

[keys.insert]
C-s = ["normal_mode", ":write"]
# "" = "normal_mode"
# h = { h = "normal_mode" }
# i = { i = "normal_mode" }

[keys.select]
i = "extend_visual_line_up"
k = "extend_visual_line_down"
j = "extend_char_left"
l = "extend_char_right"

[keys.normal.g]
j = "goto_line_start"

[keys.normal.C-w]
j = "jump_view_left"

[keys.normal."space".w]
j = "jump_view_left"

[keys.normal.";"]
s = ":w"
c = ":buffer-close"
