[alacritty.files]
"config/alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[starship.files]
"config/starship/starship.toml" = "~/.config/starship.toml"

[wezterm.files]
"config/wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"

[zed.files]
"config/zed/keymap.json" = "~/.config/zed/keymap.json"
"config/zed/settings.json" = "~/.config/zed/settings.json"

[zellij.files]
"config/zellij/config.kdl" = "~/.config/zellij/config.kdl"

[zsh.files]
zshrc = "~/.zshrc"
