[alacritty.files]
"config/alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[broot.files]
"config/broot/conf.hjson" = "~/.config/broot/conf.hjson"
"config/broot/verbs.hjson" = "~/.config/broot/verbs.hjson"

[ghostty.files]
"config/ghostty/config" = "~/.config/ghostty/config"

[helix.files]
"config/helix/config.toml" = "~/.config/helix/config.toml"
"config/helix/languages.toml" = "~/.config/helix/languages.toml"

[scripts.files]
"scripts/open-in-helix.sh" = "~/.local/bin/open-in-helix.sh"

[starship.files]
"config/starship/starship.toml" = "~/.config/starship.toml"

[wezterm.files]
"config/wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"

[yazi.files]
"config/yazi/yazi.toml" = "~/.config/yazi/yazi.toml"
"config/yazi/keymap.toml" = "~/.config/yazi/keymap.toml"

[zed.files]
"config/zed/keymap.json" = "~/.config/zed/keymap.json"
"config/zed/settings.json" = "~/.config/zed/settings.json"

[zellij.files]
"config/zellij/config.kdl" = "~/.config/zellij/config.kdl"

[zsh.files]
zshrc = "~/.zshrc"
