[[manager.prepend_keymap]]
on = "i"
run = 'arrow -1'

[[manager.prepend_keymap]]
on = "k"
run = 'arrow 1'

[[manager.prepend_keymap]]
on = "j"
run = 'leave'

[[manager.prepend_keymap]]
on = "l"
run = 'enter'
